spring:
  datasource:
    url: ${JDBC_DEVIT_URL:jdbc:oracle:thin:@localhost:1521:xe}
    username: ${JDBC_DEVIT_USERNAME:sys as sysdba}
    password: ${JDBC_DEVIT_PASSWORD:<<YOUR_PASSWORD>>}
    type: oracle.ucp.jdbc.PoolDataSource
    oracleucp:
      minPoolSize: 4
      maxPoolSize: 20
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
springdoc:
  pathsToMatch: /, /api/**
