spring:
  datasource:
    url: ${JDBC_DEVIT_URL}
    username: ${JDBC_DEVIT_USERNAME}
    password: ${JDBC_DEVIT_PASSWORD}
    type: oracle.ucp.jdbc.PoolDataSource
    oracleucp:
      minPoolSize: 4
      maxPoolSize: 20
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
        format_sql: true
        default_schema: DEVIT_
  sql:
    init:
      mode: always

database:
  schema: DEVIT_

error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
springdoc:
  pathsToMatch: /, /api/**
